fastlane_version '2.53.1'

# TUTORIAL
# https://carloscuesta.me/blog/shipping-react-native-apps-with-fastlane
# https://docs.fastlane.tools/getting-started/cross-platform/react-native/

before_all do
  ensure_git_branch
  ensure_git_status_clean
  git_pull
end

platform :ios do
   # iOS Lanes
end

platform :android do
  # Android Lanes
end