#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "\nCHECKING STAGED FILES...\n"

notify_error() {
    echo "\nPLEASE CHECK ERRORS 🛑\n"
    exit 1
}

npm run check:staged || notify_error

echo "\nFILES OK. GOOD JOB 👍\n"
