name: RN CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: cache node_modules
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-${{ hashFiles('**/package.json') }}
          path: |
            node_modules
      - name: install latest npm
        run: |
          npm install -D npm &&
          ./node_modules/.bin/npm --version
      - name: install dependencies
        run: |
          ./node_modules/.bin/npm install

  lint:
    needs:
      - install_dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: cache node_modules
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-${{ hashFiles('**/package.json') }}
          path: |
            node_modules
      - name: lint (CHECK FOR WARNINGS ✋)
        run: npm run lint:all

  tests:
    needs:
      - install_dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: cache node_modules
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-${{ hashFiles('**/package.json') }}
          path: |
            node_modules
      - name: run tests
        run: npm run test:ci

  build_ios:
    needs:
      - install_dependencies
      - lint
      - tests
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          check-latest: true
      - name: install latest npm
        run: |
          npm install -D npm &&
          ./node_modules/.bin/npm --version
      - name: install dependencies
        run: |
          ./node_modules/.bin/npm install
      - name: install pods
        run: bash ./.scripts/ios-podinstall.sh
