name: RN CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: "npm"
      - name: cache node_modules
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-${{ hashFiles('**/package.json') }}
          path: |
            node_modules
      - name: update npm
        run: sudo npm install -g npm
      - name: install dependencies
        run: npm install

  lint:
    needs:
      - install_dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: "npm"
      - name: cache node_modules
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-${{ hashFiles('**/package.json') }}
          path: |
            node_modules
      - name: lint
        run: npm run lint:all

  tests:
    needs:
      - install_dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: "npm"
      - name: cache node_modules
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-${{ hashFiles('**/package.json') }}
          path: |
            node_modules
      - name: lint
        run: npm run test:ci
