name: RN Release CI

on:
  push:
    tags:
      - v**
  
jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - uses: cache node_modules
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          path: |
            ./node_modules
      - name: install latest npm
        run: |
          npm install -g npm &&
          echo "CURRENT NPM VERSION ($(npm --version)) NODE ($(node --version))" &&
          npm list -g --depth 0
      - name: install dependencies
        run: | 
          npm install